server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always

spring:

  datasource:
    password: League24.98
    url:  jdbc:mysql://localhost:3306/linktree
    username: root
    initialization-mode: always
  jpa:


    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: onlinevehicleshop@gmail.com
    password: sdfwszifyneaajej

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000





